### ISSUE TITLE
nosetup should not prevent traversal of module tree

### ISSUE THREAD

**Issue by jjts** [IObundle/py2hwsw#101]
nosetup should be passed recursively and all modules in tree should be evaluated without copying files to build directory

**Comment by arturum1** [comment]
The "nosetup" attribute should be deprecated.

The current issue with the wrappers will be resolved by creating a new `superblocks` list dedicated for wrappers of the python topmodule.

For example, iob_system will have a `subblocks` list with components like, cpu, interconnect, peripherals, ...
It will also have a `superblocks` list with wrappers like the `iob_system_sim.py`, `iob_system_aes_ku040_db_g.py`, ...

Some cores like iob-uart will also have a `superblocks` list with their own simulation/board wrappers.
Note however that these superblocks will not be setup if the iob-uart is not the top module.
We dont want to setup uart simulation wrappers when we are running an iob-soc as the top module.
