### ISSUE TITLE
Setting default values of FSM signals.

### ISSUE THREAD

**Issue by arturum1** [IObundle/py2hwsw#30]
https://github.com/IObundle/py2hwsw/blob/cdf1b1242d24198aa56d464ab9f525be1172754e/py2hwsw/scripts/iob_fsm.py#L43-L48
Currently, `pc_nxt` is the only FSM signal that has a (hardcoded) default value:
```
pc_nxt = pc + 1;
```
It would be nice to have a way of configuring default values for other FSM signals, like the [ones from the `iob_div_subshift_frac`](https://github.com/IObundle/iob-soc/blob/de58afcc6f0f45b5491be576f371fda65ca93636/submodules/LIB/hardware/modules/div/iob_div_subshift_frac/hardware/src/iob_div_subshift_frac.v#L78-L80) module.

**Comment by jjts** [comment]
This is a very valid issue, but relevant for iob_comb, from which fsm should be derived
