### ISSUE TITLE
Fix py2hwsw top module

### ISSUE THREAD

**Issue by arturum1** [IObundle/py2hwsw#86]
Currently, py2hwsw assumes the top module is always the parent core.
To prevent issues, it should set the first core called (may be a child core) as the top module.

For example, currently, if the user starts the setup process for a Tester (child of iob_system), that includes a SUT submodule (also child of iob_system), then py2hwsw will setup the first iob_system as the top module, and will not run the setup for the second iob_system (to prevent possible infinite loops when calling top module multiple times).

This change will also require modifications to the iob_system memory wrapper.
Currently the `iob_system_mwrap.py` contains the `iob_system` block, and that block may no longer be the top module (since the new top module may be a child like the SUT).
Calling `iob_system` from the memory wrapper will cause an infinite loop since the `iob_system` also calls the memory wrapper.
To fix this, the iob_system memory wrapper should always call the top module (possibly a child core), and not be hardcoded to call `iob_system`.

The info about the top module (child core) may be passed via python parameters from the iob_system to the memory wrapper.

**Comment by jjts** [comment]
I do not understand but:

We are coding parent / child stuff when this is built-in feature when using classes.

The memory wrapper should be inserted as a final processing step for the top. Not designated to be the top.
