### ISSUE TITLE
Asym converter should have a param to switch between MSB and LSB first endianess (current is LSB first only)

### ISSUE THREAD

**Issue by AndreMerendeira** [IObundle/py2hwsw#96]
[Solve here](https://github.com/IObundle/py2hwsw/blob/main/py2hwsw/lib/hardware/buses/iob_asym_converter/hardware/src/iob_asym_converter.v)

**Comment by jjts** [comment]
currently only big endian is suported

**Comment by AndreMerendeira** [comment]
solution can be found at [AC97 Asym Converter](https://github.com/IObundle/iob-ac97/blob/main/hardware/src/iob_asym_converter.v) and [AC97 Fifo Async](https://github.com/IObundle/iob-ac97/blob/main/hardware/src/iob_fifo_async.v)
